### ISSUE TITLE
Code Generator Exception

### ISSUE THREAD

**Issue by Eden-06** [max-leuthaeuser/SCROLLGen#1]
I get the following error when generating code for [baseTest2.crom.txt](https://github.com/max-leuthaeuser/SCROLLGen/files/1611451/baseTest2.crom.txt).

```
java.lang.NoSuchMethodError: crom_l1_composed.Fulfillment.getFiller()Lcrom_l1_composed/RigidType;
	at generator.CROMGenerator$$anonfun$getFulfillments$4$$anonfun$apply$2.apply(CROMGenerator.scala:20)
	at generator.CROMGenerator$$anonfun$getFulfillments$4$$anonfun$apply$2.apply(CROMGenerator.scala:18)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at generator.CROMGenerator$$anonfun$getFulfillments$4.apply(CROMGenerator.scala:18)
	at generator.CROMGenerator$$anonfun$getFulfillments$4.apply(CROMGenerator.scala:17)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at generator.CROMGenerator$.getFulfillments(CROMGenerator.scala:17)
	at generator.CROMGenerator$.getFulfillments(CROMGenerator.scala:13)
	at templates.txt.CompartmentTypeTemplate$.apply(CompartmentTypeTemplate.template.scala:34)
	at templates.txt.CROMApplicationTemplate$$anonfun$apply$3.apply(CROMApplicationTemplate.template.scala:30)
	at templates.txt.CROMApplicationTemplate$$anonfun$apply$3.apply(CROMApplicationTemplate.template.scala:30)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at templates.txt.CROMApplicationTemplate$.apply(CROMApplicationTemplate.template.scala:30)
	at generator.CROMGenerator.generate(CROMGenerator.scala:166)
	at org.rosi.crom.toformal.generator.ScrollCodeGenerator.generate(ScrollCodeGenerator.java:16)
	at org.rosi.crom.toformal.generator.AbstractCROMGenerator.generate(AbstractCROMGenerator.java:46)
	at org.rosi.crom.toformal.popup.actions.AbstractGenerateAction.run(AbstractGenerateAction.java:84)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5268)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

**Comment by max-leuthaeuser** [comment]
Fixed with commit 4737923.
